### ISSUE TITLE
Game crashed after InsertFile

### ISSUE THREAD

**Issue by gentle-shao** [RichieSams/raflib-plus#1]
I used RAFLib-Plus(https://github.com/RichieSams/raflib-plus) to insert custom skin files.

RAFExtractor shows I replaced the files correctly,but the game crashed all the time when I try.

Here's the code:

```
private void button5_Click(object sender, EventArgs e)
    {
        string league_path = "C:\\Riot Games\\League of Legends\\RADS\\projects\\lol_game_client\\filearchives";
        RAFMasterFileList RAFMasterFileList = new RAFMasterFileList(league_path);
        List<string> entry = RAFMasterFileList.GetRAFFiles(league_path);
        entry.ForEach(raf_access);
    }
```

    private static void raf_access(string s)
    {
        bool content_changed = false;
        string[] fileEntries = Directory.GetFiles(Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location) + "\\DATA", "*", SearchOption.AllDirectories);
        //Console.WriteLine(s);
        RAFArchive RAFArchive = new RAFArchive(s);

        Dictionary<string, RAFFileListEntry> entries = RAFArchive.FileDictFull;
        foreach (KeyValuePair<string, RAFFileListEntry> entry in entries)
        {
            foreach (string fileName in fileEntries)
            {
                string correct_name;
                correct_name = fileName.Replace(Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location), "").Replace("\\", "/").Substring(1);
                if( correct_name.ToLower() == entry.Key )
                {
                    content_changed = true;
                    if (RAFArchive.InsertFile(correct_name, File.ReadAllBytes(fileName), false))
                    {
                        Console.Write("\n");
                        Console.Write(correct_name);
                    }
                }
            }
        }
        if(content_changed)
        {
            RAFArchive.SaveRAFFile();
            Console.Write("\n");
            Console.Write(RAFArchive.RAFFilePath + " saved.");
        }

    }`

and here's some of error log:
`000016.279| ERROR| Riot::RADS::Reader::DecompressZlib: Decompress ran out of sink buffer space: not all compressed data was consumed (11341 B read). 000016.279| ERROR| Riot::RADS::Reader::ProjectListing::ArchiveFile::LogFailure: Failed to decompress archive file "DATA/Characters/Ashe/Skins/Base/Particles/Ashe_Base_Q_flying_shards.dds" from "C:/Riot Games/League of Legends/RADS/projects/lol_game_client/filearchives/0.0.1.29/Archive_1.raf.dat", version=0.0.1.29, compressionId=1112099930, offset=21023779, archiveSize=16880, entrySize=65664. 000016.279| ERROR| Riot::RADS::Reader::ProjectListing::ArchiveFile::LogCompressedData: 78 9C EC 7D 0D 74 13 D7 99 F6 D5 8C 6C EB C7 FA B1 8D B1 F9 CD 08 6C 04 38 C2 D0 C6 01 E7 07 29 x..}.t......l.........l.8......)`

I'm very sure files in fileEntries are fine. But I can't figure out what's wrong here.

**Comment by RichieSams** [comment]
Unfortunately, this library is no longer valid for LoL file modding. The RAF files now have duplicates, and the game uses a manifest file to differentiate between the duplicates. Also, it seems to have some kind of checksumming / duplication of data location within the raf.dat between the raf files and the manifest. Because, if you just edit the RAF (as RAFLib-Plus does), the game will crash, because the manifest will point to a different location.

So sorry, this library will no longer work.
